apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testx
  name: testx
spec:
  containers:
  - image: nginx
    name: testx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
