apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: testx2
  name: testx2
  namespace: default
spec:
  containers:
  - image: busybox
    name: testx2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
