apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: testx
  name: test1svc
spec:
  ports:
  - name: 5678-8081
    port: 5678
    protocol: TCP
    targetPort: 80
    nodePort: 31803
  selector:
    app: test1svc
  type: NodePort
status:
  loadBalancer: {}
